"""
Shared fixtures for the remediation test suite.

Loading a pedigree has two side effects that make naive tests hostile to the
working tree: ``NewPedigree.__init__`` installs a PyPedal-owned logfile
handler, and the analysis routines write ``<filetag>_*.dat`` files derived
from the pedfile path.

``filetag`` is overwritten unconditionally from ``kw['pedfile']``
(``pyp_newclasses.py:86``), so passing a ``filetag`` option does not redirect
that output. The only reliable way to keep a test run from writing into
the working tree is to copy the pedigree into a temporary directory
and load it from there, which is what ``load_corpus`` does. That also
guarantees the bytes fed to the loader are identical to the committed fixture.
"""
import contextlib
import logging
import os
import shutil
import tempfile

from PyPedal.pyp_newclasses import (
    PYPEDAL_LOGGER_NAME,
    _PYPEDAL_OWNED_HANDLER,
    load_pedigree,
)

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
EXAMPLES = os.path.join(REPO, "PyPedal", "examples")
CORPUS = os.path.join(REPO, "tests", "fixtures", "pedigrees")

# The corpus pedigrees used by the remediation tests, with the pedformat each
# one actually requires. Getting these wrong produces an empty pedigree and a
# vacuously passing test, so they are stated once, here.
PEDFORMATS = {
    "mrode.ped": "asd",
    "new_lacy.ped": "asd",
    "generations.ped": "asdbx",
    "hartlandclark.ped": "asdb",
    "boichard2a.ped": "asdg",
    "doug.ped": "ASDx",
    "new_ids.ped": "ASD",
    "userfield.ped": "asdu",
    # Published worked examples transcribed from the primary sources. Each file
    # carries its own provenance header naming the figure, table and page.
    "boichard_fig1.ped": "asdg",
    "boichard_fig2.ped": "asdg",
    "ballou_fig1.ped": "asd",
    "suwanlee_fig1.ped": "asd",
}


def corpus(name):
    return os.path.join(CORPUS, name)


def load_corpus_from_path(path, pedformat, sepchar=" ", **overrides):
    """
    Load an arbitrary pedigree file, for purpose-built fixtures generated by a
    test. Output is confined the same way ``load_corpus`` confines it.
    """
    tmp = tempfile.mkdtemp(prefix="pypedal_test_")
    local = os.path.join(tmp, os.path.basename(path))
    shutil.copy(path, local)
    return _load(local, pedformat, sepchar, tmp, overrides)


def load_corpus(name, pedformat=None, sepchar=" ", **overrides):
    """Load a corpus pedigree with all generated output confined to a tmpdir."""
    tmp = tempfile.mkdtemp(prefix="pypedal_test_")
    local = os.path.join(tmp, name)
    shutil.copy(corpus(name), local)
    return _load(local, pedformat or PEDFORMATS[name], sepchar, tmp, overrides)


def _load(local, pedformat, sepchar, tmp, overrides):
    options = {
        "pedfile": local,
        "pedformat": pedformat,
        "sepchar": sepchar,
        "messages": "quiet",
        "renumber": True,
        "pedigree_is_renumbered": True,
        "pedigree_summary": 0,
    }
    options.update(overrides)
    cwd = os.getcwd()
    try:
        # Some routines write relative to the working directory rather than to
        # filetag; run the load from inside the tmpdir so those land there too.
        os.chdir(tmp)
        ped = load_pedigree(options)
    finally:
        os.chdir(cwd)
    # FileHandler is on the PyPedal logger; keep pytest output clean.
    logging.disable(logging.CRITICAL)
    return ped


def close_owned_pypedal_log_handlers():
    """Close PyPedal-owned logfile handlers so tests can delete temp logs.

    Only handlers marked with the production ``_pypedal_owned`` flag are
    removed. Host application handlers and the root logger are untouched.
    Does not call ``logging.shutdown()``.
    """
    package = logging.getLogger(PYPEDAL_LOGGER_NAME)
    for handler in list(package.handlers):
        if getattr(handler, _PYPEDAL_OWNED_HANDLER, False):
            package.removeHandler(handler)
            handler.close()


def write_temp_pedigree(rows, suffix=".ped"):
    """Write pedigree rows to a new temp file whose handle is already closed.

    ``tempfile.mkstemp`` leaves an open fd; Windows cannot delete that
    path until the fd is closed. Tests that later ``os.remove`` the file
    must not keep that descriptor.
    """
    fd, path = tempfile.mkstemp(suffix=suffix)
    os.close(fd)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(rows) + "\n")
    return path


@contextlib.contextmanager
def chdir_tmp():
    """
    Run a block with the working directory set to a fresh temporary directory.

    Several routines write output relative to the *working directory* rather
    than to ``filetag`` -- ``pyp_utils.fast_reorder(io='yes')`` writes
    ``_new_reordered__reordered.ped`` and ``_new_reordered__id_map.map``, and
    ``pyp_utils.renumber(io='yes')`` with no ``filetag`` writes
    ``_renumbered__renum.ped`` and ``_renumbered__id_map.map``. A test that
    asserts on those filenames therefore has to control the working directory,
    or it both depends on where pytest was invoked from and litters the
    repository. Yields the temporary directory.
    """
    tmp = tempfile.mkdtemp(prefix="pypedal_test_")
    cwd = os.getcwd()
    try:
        os.chdir(tmp)
        yield tmp
    finally:
        os.chdir(cwd)
        shutil.rmtree(tmp, ignore_errors=True)


def load_example(name, options):
    """
    Load a pedigree from ``PyPedal/examples`` with all generated output confined
    to a temporary directory.

    Unlike ``load_corpus``, this injects **no** options of its own: ``options``
    is used verbatim apart from ``pedfile``, which is repointed at a temporary
    copy of the named example. That keeps the behaviour of an existing test
    identical while stopping it from writing into the source tree -- ``filetag``
    is derived from the pedfile path (``pyp_newclasses.py:86``), so moving the
    input moves the output with it.
    """
    tmp = tempfile.mkdtemp(prefix="pypedal_test_")
    local = os.path.join(tmp, name)
    shutil.copy(os.path.join(EXAMPLES, name), local)
    opts = dict(options)
    opts["pedfile"] = local
    cwd = os.getcwd()
    try:
        os.chdir(tmp)
        ped = load_pedigree(opts)
    finally:
        os.chdir(cwd)
    logging.disable(logging.CRITICAL)
    return ped


def nrm_value(a, i, j):
    """Read A[i, j] from a matrix that may be dense NumPy or SciPy sparse."""
    v = a[i, j]
    try:
        return float(v)
    except (TypeError, ValueError):
        return float(v.toarray()[0, 0])


# ---------------------------------------------------------------------------
# Griffon Bruxellois sample
# ---------------------------------------------------------------------------
# The repository ships two Griffon pedigree datasets with identical
# genealogical structure:
#     PyPedal/examples/griffonbruxellois_2026_pyp.ped      (asdxb, science)
#     PyPedal/examples/griffonbruxellois_2026_named_pyp.ped (asdxbn, desktop names)
# Scientific tests that historically used a small extract derive that extract
# into a temporary directory from the canonical scientific file. The ID sets
# below are the animals that were present in the deleted checked-in extracts;
# they are not a year-window rule. Do not invent parents. Dangling references
# that existed in the old extracts are preserved so load-time implicit-parent
# behaviour stays identical.

CANONICAL_GRIFFON_PED = "griffonbruxellois_2026_pyp.ped"
NAMED_GRIFFON_PED = "griffonbruxellois_2026_named_pyp.ped"

# Tiny named pedigree used by animal-lookup tests. Two animals share the
# display name "Bella" with different original IDs, current IDs, and birth years.
NAMED_DUPLICATE_PED = """\
101,0,0,f,01012019,Bella
102,0,0,m,01012020,Max
103,101,102,f,01012021,Bella
104,101,102,m,01012023,Spot
105,0,0,m,01012018,
"""


# Former griffons-1871-1890.ped. Animal 32240 is a dangling sire of 28806
# (present in the canonical file, omitted here) so a default load still
# materializes one implicit parent and n == 167.
GRIFFON_1871_1890_IDS = frozenset((
    31159, 87321, 88266, 88257, 68440, 74245, 31167, 88501, 43746, 17637,
    31162, 31229, 11089, 31160, 10917, 37272, 20823, 17113, 88504, 47819,
    44647, 58438, 58413, 55406, 60184, 28903, 17992, 31168, 21451, 58409,
    58478, 55435, 58289, 58429, 58614, 58406, 57266, 20198, 9458, 30209,
    28859, 30584, 88253, 88263, 98136, 31169, 31179, 55351, 58319, 57271,
    70500, 29033, 27223, 37283, 11446, 11051, 24638, 10926, 30970, 28806,
    24654, 34009, 78439, 82449, 51488, 60194, 57666, 60224, 70353, 58456,
    44786, 58342, 49214, 55419, 76319, 58441, 87912, 17079, 58354, 11090,
    88255, 88979, 88326, 88274, 98642, 88251, 11473, 21404, 8994, 31165,
    9366, 10706, 28910, 20924, 20822, 24659, 55380, 55418, 58283, 44668,
    55395, 43747, 57641, 28893, 55692, 88644, 58287, 32403, 23570, 16546,
    13311, 32245, 30978, 96104, 87614, 69792, 58290, 55376, 58434, 49267,
    58309, 57248, 58423, 58439, 74273, 87710, 87721, 88282, 10925, 88518,
    92229, 96101, 87568, 88261, 88265, 88260, 31166, 32406, 24672, 13286,
    31161, 13572, 31164, 28901, 30083, 13292, 13295, 29113, 54830, 58470,
    58428, 55433, 54837, 78790, 55446, 60870, 60864, 54810, 88256, 60304,
    2122, 47793, 2055, 17111, 87996, 46000,
))

# Former griffons_test_small.ped. Parents of these 18 animals that are not in
# the set remain dangling so the load still materializes implicit parents.
GRIFFON_TEST_SMALL_IDS = frozenset((
    98647, 98648, 98649, 98650, 98652, 98653, 98654, 98655, 98657, 98658,
    98659, 98660, 98661, 98662, 98663, 98664, 98665, 98666,
))

_GRIFFON_ASDXB = {
    "pedformat": "asdxb",
    "sepchar": ",",
    "messages": "quiet",
    "renumber": True,
    "pedigree_is_renumbered": True,
    "pedigree_summary": 0,
}


def canonical_griffon_path():
    return os.path.join(EXAMPLES, CANONICAL_GRIFFON_PED)


def write_canonical_griffon_subset(dest_path, original_ids):
    """Copy matching records from the canonical Griffon file.

    Writes only under ``dest_path`` (caller-owned temporary location).
    Source lines are copied verbatim so sire, dam, sex, and date tokens
    match the canonical sample. Missing IDs are an error: the helper must
    not invent parents or silently drop animals.
    """
    wanted = {str(int(i)) for i in original_ids}
    found = set()
    dest_dir = os.path.dirname(os.path.abspath(dest_path))
    os.makedirs(dest_dir, exist_ok=True)
    with open(canonical_griffon_path(), encoding="utf-8") as src:
        with open(dest_path, "w", encoding="utf-8") as dst:
            for line in src:
                if not line.strip():
                    continue
                animal_id = line.split(",", 1)[0]
                if animal_id in wanted:
                    dst.write(line if line.endswith("\n") else line + "\n")
                    found.add(animal_id)
    missing = wanted - found
    extra = found - wanted
    if missing or extra:
        raise ValueError(
            "canonical Griffon subset mismatch: missing=%s extra=%s"
            % (sorted(missing, key=int)[:20], sorted(extra, key=int)[:20])
        )
    return dest_path


def _load_griffon_subset(original_ids, dest_name, options=None):
    tmp = tempfile.mkdtemp(prefix="pypedal_test_")
    local = os.path.join(tmp, dest_name)
    write_canonical_griffon_subset(local, original_ids)
    opts = dict(_GRIFFON_ASDXB)
    if options:
        opts.update({key: value for key, value in options.items() if key != "pedfile"})
    opts["pedfile"] = local
    cwd = os.getcwd()
    try:
        os.chdir(tmp)
        ped = load_pedigree(opts)
    finally:
        os.chdir(cwd)
    logging.disable(logging.CRITICAL)
    return ped


def load_griffon_1871_1890(options=None):
    """Load the historical 1871–1890 characterisation cohort from canonical."""
    return _load_griffon_subset(
        GRIFFON_1871_1890_IDS, "griffon_1871_1890.ped", options
    )


def load_griffon_test_small(options=None):
    """Load the historical 18-animal Griffon extract from canonical."""
    return _load_griffon_subset(
        GRIFFON_TEST_SMALL_IDS, "griffon_test_small.ped", options
    )


def load_canonical_griffon(options=None):
    """Load the checked-in Griffon 2026 export with true ``asdxb`` chronology."""
    opts = dict(_GRIFFON_ASDXB)
    if options:
        opts.update(options)
    return load_example(CANONICAL_GRIFFON_PED, opts)


def named_griffon_path():
    return os.path.join(EXAMPLES, NAMED_GRIFFON_PED)


def load_named_griffon(options=None):
    """Load the named Griffon 2026 export (``asdxbn`` display names)."""
    opts = dict(_GRIFFON_ASDXB)
    opts["pedformat"] = "asdxbn"
    if options:
        opts.update(options)
    return load_example(NAMED_GRIFFON_PED, opts)

