#!/usr/bin/env python3
"""
INDEPENDENT oracle for BOICHARD's N_g -- the effective number of
founder genomes remaining in the population under study.

Does not import PyPedal. Does not import, wrap or consult
``oracle_lacy.f_g_lacy``.

    Boichard D, Maignel L, Verrier E (1997) "The value of using probabilities
    of gene origin to measure genetic variability in a population."
    Genet Sel Evol 29:5-23.  Article p.10-11 (PDF p.7-8), equation [2]:

        N_a = 1 / SUM_{k=1..2f} f_k^2
        N_g = N_a / 2 = 1 / (2 * SUM_{k=1..2f} f_k^2)

    "At a given locus, each founder is characterized by its two genes and 2f
    founder genes are generated. Then the segregation is simulated throughout
    the complete pedigree and the genotype of each progeny is generated by
    randomly sampling one allele from each parent. Gene frequencies f_k are
    determined by gene counting in the population under study."

THIS IS NOT LACY'S f_g -- AND THAT IS THE POINT OF THE MODULE
--------------------------------------------------------------
Boichard p.11 calls N_g the quantity "called 'founder genome equivalent' by
Lacy, 1989". That is a NAMING claim in passing; the paper derives no equivalence
and the two are different functionals:

    Lacy (1989) p.115      f_g = 1 / SUM (p_i^2 / r_i)
                           r_i = expected proportion of founder i's alleles
                                 RETAINED (a survival probability)

    Boichard (1997) eq.2   N_g = 1 / (2 * SUM f_k^2)
                           f_k = FREQUENCY of founder gene k in R

Lacy p.117-118 confirms his own estimator is the retention one: "Analysis of
founder allele *retention* in 10,000 gene drop computer simulations yielded
23.79 founder genome equivalents". ``test_founder_genomes_oracle.py`` pins the
resulting numerical disagreement on Lacy's own published Table 1 and on
``new_lacy.ped``, so that no later reader can quietly substitute one for the
other. Use ``oracle_lacy.f_g_lacy`` for f_g. Use this module for N_g. Never one
as the oracle for the other.

CALIBRATION, AND THE LIMIT OF WHAT IT PROVES
--------------------------------------------
``gene_diversity()`` reproduces Lacy's Table 1 column H, which he obtained from
10 000 gene-drop simulations. That agreement validates the SEGREGATION AND
GENE-COUNTING MECHANICS of this module -- nothing more. It emphatically does
NOT show that Lacy f_g equals Boichard N_g; on the very same pedigrees the two
disagree by 8-11%.

BOUNDS
------
``N_g >= 0.5``, not ``>= 1``. With f_k >= 0 and SUM f_k = 1 we have
0 < SUM f_k^2 <= 1, so N_g = 1/(2 SUM f_k^2) >= 1/2, with equality exactly when
one founder gene is FIXED in R. A fixed founder gene is a legitimate outcome of
gene dropping, so ``N_g < 1`` is a valid result and must never be rejected.

``N_g <= f_e`` holds PER REPLICATE against the f_e computed from the SAME
realised frequencies, by (a+b)^2 <= 2(a^2+b^2) applied to p_i = f_i1 + f_i2:

    SUM_i p_i^2 <= 2 SUM_k f_k^2   =>   N_g = 1/(2 SUM f_k^2) <= 1/SUM p_i^2 = f_e

with equality exactly when every founder's two genes are equally frequent in R.
``f_e_realised()`` computes that same-replicate f_e so the gate is exact rather
than an appeal to Boichard's Table II. The relation between E[N_g] and the
NRM-based *expected* f_e does NOT follow from this derivation and is reported as
an observation, never enforced.
"""
import argparse
import json
import os
import random
import sys
from fractions import Fraction

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from oracle_boichard import (  # noqa: E402
    MISSING,
    check_topological,
    read_pedigree,
    unknown_parent_slots,
)

#: Half-founder representations. Both are *research* representations; neither is
#: a production decision. See FG-10 in the Finding-31 document.
HALF_FOUNDER_MODES = ("phantom", "slot")

#: Exhaustive enumeration is 2**(number of binary segregation choices). The cap
#: is a refusal threshold, not a silent fallback: past it the caller must ask
#: for Monte Carlo explicitly, so that an "exact" label is never attached to a
#: sampled result.
DEFAULT_EXACT_LIMIT = 1 << 20


class ExactEnumerationTooLarge(Exception):
    """Raised instead of silently sampling when the state space exceeds the cap."""


# ---------------------------------------------------------------------------
# pedigree structure
# ---------------------------------------------------------------------------

def true_founders(rows):
    """
    Animals with BOTH parents unknown.

    Deliberately different from ``oracle_boichard.founders``, which implements
    Boichard p.7's founder definition for the f_e/f_a bounds and therefore
    counts half-founders as founders. Gene dropping needs the animals that
    actually originate two founder genes, which a half-founder does not: it
    originates one, through its unknown parental side.
    """
    return [a for a, s, d in rows if s == MISSING and d == MISSING]


def founder_genes(rows, half_founder="phantom"):
    """
    The ``2f`` founder genes of eq. 2, as ordered labels.

    ``phantom``  each unknown parental slot is its own founder with two unique
                 genes (Lacy p.113; Boichard App. A step 4; Baumung 2015 p.102).
    ``slot``     each unknown parental slot contributes exactly ONE unique gene,
                 placed directly in the slot.

    FG-10 asks whether the two give the same distribution of SUM f_k^2. They
    generate DIFFERENT numbers of labels, which is precisely why the question is
    about the distribution of the statistic and not about the label count.
    """
    if half_founder not in HALF_FOUNDER_MODES:
        raise ValueError("half_founder must be one of {!r}".format(HALF_FOUNDER_MODES))
    genes = []
    for a in true_founders(rows):
        genes.extend(["F%d.1" % a, "F%d.2" % a])
    for a, side in unknown_parent_slots(rows):
        if half_founder == "phantom":
            genes.extend(["P%d%s.1" % (a, side[0]), "P%d%s.2" % (a, side[0])])
        else:
            genes.append("P%d%s" % (a, side[0]))
    return genes


def _choice_plan(rows, half_founder):
    """
    One entry per animal that is not a true founder, as
    ``(animal, sire_source, dam_source)`` where each source is either

        ('parent', parent_id)        sample one of that parent's two genes
        ('phantom', (g1, g2))        sample one of the phantom founder's genes
        ('fixed', g)                 no choice at all -- the slot's single gene

    The number of binary choices is the number of non-``fixed`` sources, and
    that is what sizes the exhaustive enumeration.
    """
    plan = []
    for a, s, d in rows:
        if s == MISSING and d == MISSING:
            continue
        sources = []
        for parent, side in ((s, "sire"), (d, "dam")):
            if parent != MISSING:
                sources.append(("parent", parent))
            elif half_founder == "phantom":
                sources.append(("phantom", ("P%d%s.1" % (a, side[0]),
                                            "P%d%s.2" % (a, side[0]))))
            else:
                sources.append(("fixed", "P%d%s" % (a, side[0])))
        plan.append((a, sources[0], sources[1]))
    return plan


def n_binary_choices(rows, half_founder="phantom"):
    return sum(1
               for _a, s0, s1 in _choice_plan(rows, half_founder)
               for src in (s0, s1)
               if src[0] != "fixed")


def _segregate(rows, plan, bits, geno=None):
    """
    Realise one gene drop. ``bits`` is an iterable of 0/1 consumed in plan
    order; ``rows`` must be topologically ordered so a parent's genotype exists
    before it is sampled.

    ``geno`` seeds the founder genotypes. It defaults to the true founders of
    ``rows``; ``distribution()`` passes its own, because the rows it enumerates
    deliberately exclude founders and animals it has factorised out.
    """
    geno = dict(geno) if geno is not None else {}
    for a in true_founders(rows):
        geno[a] = ("F%d.1" % a, "F%d.2" % a)
    it = iter(bits)
    for a, src0, src1 in plan:
        got = []
        for kind, payload in (src0, src1):
            if kind == "fixed":
                got.append(payload)
            elif kind == "phantom":
                got.append(payload[next(it)])
            else:
                got.append(geno[payload][next(it)])
        geno[a] = (got[0], got[1])
    return geno


# ---------------------------------------------------------------------------
# the statistic
# ---------------------------------------------------------------------------

def gene_counts(geno, reference):
    """Gene counting in the population under study (eq. 2's ``f_k``, unnormalised)."""
    counts = {}
    for a in reference:
        for g in geno[a]:
            counts[g] = counts.get(g, 0) + 1
    return counts


def sum_f2(geno, reference):
    """SUM_{k=1..2f} f_k^2, exactly, as a Fraction."""
    counts = gene_counts(geno, reference)
    n = sum(counts.values())
    if n == 0:
        raise ValueError("the population under study contains no gene copies; "
                         "SUM f_k^2 is undefined")
    return Fraction(sum(c * c for c in counts.values()), n * n)


def ng(geno, reference):
    """Per-replicate N_g = 1/(2 SUM f_k^2), exactly, as a Fraction."""
    return 1 / (2 * sum_f2(geno, reference))


def gene_diversity(geno, reference):
    """
    1 - SUM f_k^2, the gene diversity of R. Lacy's Table 1 column H is the mean
    of this over his 10 000 simulations, and reproducing it calibrates the
    segregation and counting mechanics of this module -- and nothing else.
    """
    return 1 - sum_f2(geno, reference)


def f_e_realised(geno, reference):
    """
    f_e computed from the SAME realised frequencies as ``ng``, i.e.
    1/SUM_i p_i^2 with p_i = f_i1 + f_i2 pooled over founder i's two genes.

    This is the only f_e against which ``N_g <= f_e`` is a derived inequality
    rather than an observation. It is NOT PyPedal's f_e, which uses expected
    contributions from the numerator relationship matrix.
    """
    counts = gene_counts(geno, reference)
    n = sum(counts.values())
    per_founder = {}
    for g, c in counts.items():
        origin = g.split(".")[0]
        per_founder[origin] = per_founder.get(origin, 0) + c
    total = sum(Fraction(c, n) ** 2 for c in per_founder.values())
    return 1 / total


# ---------------------------------------------------------------------------
# exact enumeration
# ---------------------------------------------------------------------------

def distribution_bruteforce(rows, reference, half_founder="phantom",
                            limit=DEFAULT_EXACT_LIMIT):
    """
    The EXACT distribution of SUM f_k^2 by enumerating every segregation
    outcome, as ``{Fraction(sum_f2): Fraction(probability)}``.

    Every outcome is equally likely, so probabilities are multiples of
    ``1/2**b``; they are Fractions so that two distributions can be compared for
    exact equality rather than for closeness, which is what FG-10 needs.

    This is the DEFINITION, and it is O(2**b). ``distribution()`` computes the
    same thing far faster by factorising; the two are cross-checked against each
    other in ``tests/test_founder_genomes_oracle.py`` so that the fast path can
    never quietly diverge from the definition it claims to implement.
    """
    check_topological(rows)
    plan = _choice_plan(rows, half_founder)
    b = n_binary_choices(rows, half_founder)
    if (1 << b) > limit:
        raise ExactEnumerationTooLarge(
            "%d binary segregation choices means 2**%d = %d outcomes, above the "
            "limit of %d. Raise limit= deliberately, or use mc_ng() and label "
            "the result as sampled." % (b, b, 1 << b, limit))
    dist = {}
    for mask in range(1 << b):
        bits = [(mask >> i) & 1 for i in range(b)]
        s = sum_f2(_segregate(rows, plan, bits), reference)
        dist[s] = dist.get(s, 0) + 1
    total = Fraction(1, 1 << b)
    return {s: c * total for s, c in dist.items()}


def _binomial_row(m):
    """``[(k, C(m,k)/2**m) for k in 0..m]`` as exact Fractions."""
    row, c = [], 1
    for k in range(m + 1):
        row.append((k, Fraction(c, 1 << m)))
        c = c * (m - k) // (k + 1)
    return row


def distribution(rows, reference, half_founder="phantom", limit=DEFAULT_EXACT_LIMIT):
    """
    The EXACT distribution of SUM f_k^2, factorised.

    Identical output to ``distribution_bruteforce`` -- same Fractions, same
    keys -- but it does not enumerate 2**b outcomes.

    THE FACTORISATION. Members of R that are nobody's parent are conditionally
    independent given their parents' genotypes, and members sharing a parent
    pair are exchangeable: only HOW MANY of them drew each parental gene matters
    to a gene count, not which. So a group of ``m`` such full sibs contributes
    ``Binomial(m, 1/2)`` copies of each parent's first gene rather than 2**(2m)
    enumerated outcomes. Animals that are parents, and animals with an unknown
    parental slot (whose phantom genes are unique per animal and therefore not
    exchangeable), are still enumerated exhaustively.

    Boichard's Family 1 drops from 2**20 outcomes to 16 x 81; Lacy's Table 1
    row (4,8) from 2**24 to 25 x 81.
    """
    check_topological(rows)
    if half_founder not in HALF_FOUNDER_MODES:
        raise ValueError("half_founder must be one of {!r}".format(HALF_FOUNDER_MODES))
    reference = list(reference)
    if not reference:
        raise ValueError("the population under study is empty; "
                         "SUM f_k^2 is undefined")

    parents_of_someone = set()
    for _a, s, d in rows:
        for p in (s, d):
            if p != MISSING:
                parents_of_someone.add(p)
    founders = set(true_founders(rows))
    ref = set(reference)

    #: exchangeable only if both parents are known -- a phantom gene is unique
    #: to its own animal, so half-founders are never interchangeable.
    def groupable(a, s, d):
        return (a in ref and a not in parents_of_someone and a not in founders
                and s != MISSING and d != MISSING)

    groups = {}
    enumerate_rows = []
    for a, s, d in rows:
        if a in founders:
            continue
        if groupable(a, s, d):
            groups.setdefault((s, d), []).append(a)
        elif a in parents_of_someone or a in ref:
            enumerate_rows.append((a, s, d))
        # else: not in R and nobody's parent -- affects no gene count at all

    plan = _choice_plan(enumerate_rows, half_founder)
    b = sum(1 for _a, s0, s1 in plan for src in (s0, s1) if src[0] != "fixed")
    if (1 << b) > limit:
        raise ExactEnumerationTooLarge(
            "even after factorising, %d animals must be enumerated exhaustively "
            "(2**%d = %d outcomes), above the limit of %d. Raise limit= "
            "deliberately, or use mc_ng() and label the result as sampled."
            % (len(plan), b, 1 << b, limit))

    n = 2 * len(reference)
    dist = {}
    for mask in range(1 << b):
        bits = [(mask >> i) & 1 for i in range(b)]
        seed = {}
        for f in founders:
            seed[f] = ("F%d.1" % f, "F%d.2" % f)
        geno = _segregate(enumerate_rows, plan, bits, geno=seed)

        base = {}
        for a in reference:
            if a in geno:
                for g in geno[a]:
                    base[g] = base.get(g, 0) + 1
        # {counts-tuple: probability}, convolved group by group
        genes = sorted(set(list(base)
                           + [g for (s, d) in groups for p in (s, d) for g in geno[p]]))
        idx = {g: i for i, g in enumerate(genes)}
        vec = [0] * len(genes)
        for g, c in base.items():
            vec[idx[g]] = c
        states = {tuple(vec): Fraction(1)}
        for (s, d), members in groups.items():
            m = len(members)
            nxt = {}
            for k, pk in _binomial_row(m):
                for j, pj in _binomial_row(m):
                    delta = [0] * len(genes)
                    delta[idx[geno[s][0]]] += k
                    delta[idx[geno[s][1]]] += m - k
                    delta[idx[geno[d][0]]] += j
                    delta[idx[geno[d][1]]] += m - j
                    w = pk * pj
                    for state, p in states.items():
                        key = tuple(state[i] + delta[i] for i in range(len(genes)))
                        nxt[key] = nxt.get(key, Fraction(0)) + p * w
            states = nxt
        weight = Fraction(1, 1 << b)
        for state, p in states.items():
            total = sum(state)
            if total != n:
                raise AssertionError(
                    "gene counting lost copies: %d counted, %d expected" % (total, n))
            s2 = Fraction(sum(c * c for c in state), n * n)
            dist[s2] = dist.get(s2, Fraction(0)) + p * weight
    return dist


def exact_ng(rows, reference, half_founder="phantom", limit=DEFAULT_EXACT_LIMIT):
    """
    Exhaustive enumeration. Returns a dict with

        n_g          E[1/(2 SUM f_k^2)]  -- the source estimator, see below
        inv_mean_s   1/(2 E[SUM f_k^2])  -- the OTHER candidate estimator
        e_sum_f2     E[SUM f_k^2]
        h            E[1 - SUM f_k^2], Lacy's H
        min_ng/max_ng
        outcomes     size of the enumerated state space

    WHICH ESTIMATOR IS BOICHARD'S is not a matter of taste: Table II Family 2
    publishes N_g = 1.1, and on that pedigree E[1/(2S)] = 1.1063... while
    1/(2 E[S]) = 1 exactly. Boichard averages the PER-REPLICATE N_g. ``n_g`` is
    therefore the source-consistent estimator and ``inv_mean_s`` is retained
    only so that the discriminator can be shown rather than asserted.
    """
    dist = distribution(rows, reference, half_founder, limit)
    e_s = sum(p * s for s, p in dist.items())
    e_ng = sum(p / (2 * s) for s, p in dist.items())
    return {
        "n_g": float(e_ng),
        "n_g_exact": e_ng,
        "inv_mean_s": float(1 / (2 * e_s)),
        "e_sum_f2": float(e_s),
        "h": float(1 - e_s),
        "min_ng": float(min(1 / (2 * s) for s in dist)),
        "max_ng": float(max(1 / (2 * s) for s in dist)),
        "outcomes": sum(1 for _ in dist),
        # the size of the definitional state space, NOT the amount of work done:
        # distribution() factorises exchangeable full sibs away. The two agree
        # exactly -- see the brute-force cross-check in the oracle test.
        "state_space": 1 << n_binary_choices(rows, half_founder),
        "method": "exact (factorised enumeration)",
    }


# ---------------------------------------------------------------------------
# Monte Carlo
# ---------------------------------------------------------------------------

def mc_ng(rows, reference, replicates, seed, half_founder="phantom"):
    """
    Monte-Carlo estimate, for pedigrees whose state space exceeds the exact cap.

    Uses a LOCAL ``random.Random(seed)``: this module never touches the process
    -global random state, which is one of the defects it exists to characterise.
    Returns the mean and the sample variance of the per-replicate N_g, so that
    a caller can state a tolerance from the measured variance instead of from a
    hopeful constant.
    """
    check_topological(rows)
    plan = _choice_plan(rows, half_founder)
    b = n_binary_choices(rows, half_founder)
    rng = random.Random(seed)
    total = 0.0
    total_sq = 0.0
    for _ in range(replicates):
        bits = [rng.getrandbits(1) for _ in range(b)]
        v = float(ng(_segregate(rows, plan, bits), reference))
        total += v
        total_sq += v * v
    mean = total / replicates
    var = max(0.0, total_sq / replicates - mean * mean)
    return {
        "n_g": mean,
        "variance": var,
        "sem": (var / replicates) ** 0.5,
        "replicates": replicates,
        "seed": seed,
    }


# ---------------------------------------------------------------------------
# invariant gates
# ---------------------------------------------------------------------------

def check_bounds(rows, reference, half_founder="phantom", limit=DEFAULT_EXACT_LIMIT):
    """
    Verify the two DERIVED bounds on every enumerated outcome, not on the mean.

        N_g >= 1/2                           (SUM f_k = 1, so SUM f_k^2 <= 1)
        N_g <= f_e computed from the SAME realised frequencies

    Returns ``(ok, worst_ng, min_slack)`` where ``min_slack`` is the smallest
    ``f_e - N_g`` seen; a zero slack is legal and means some outcome had every
    founder's two genes equally frequent.
    """
    check_topological(rows)
    plan = _choice_plan(rows, half_founder)
    b = n_binary_choices(rows, half_founder)
    if (1 << b) > limit:
        raise ExactEnumerationTooLarge("state space 2**%d exceeds limit %d" % (b, limit))
    worst = None
    slack = None
    for mask in range(1 << b):
        geno = _segregate(rows, plan, [(mask >> i) & 1 for i in range(b)])
        v = ng(geno, reference)
        fe = f_e_realised(geno, reference)
        if v < Fraction(1, 2):
            return False, float(v), None
        if v > fe:
            return False, float(v), float(fe - v)
        worst = v if worst is None or v < worst else worst
        d = fe - v
        slack = d if slack is None or d < slack else slack
    return True, float(worst), float(slack)


# ---------------------------------------------------------------------------
# CLI / self-test
# ---------------------------------------------------------------------------

def _parse_reference(spec):
    out = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if "-" in chunk:
            lo, hi = chunk.split("-")
            out.extend(range(int(lo), int(hi) + 1))
        elif chunk:
            out.append(int(chunk))
    return out


def _self_test():
    """
    Calibration, run without any pedigree file. Every expected value here is
    either published or derived by hand in the Finding-31 document.
    """
    failures = []

    def check(name, got, want, tol=0.0):
        ok = abs(float(got) - float(want)) <= tol
        print("  %-58s got %-12s want %-12s %s"
              % (name, round(float(got), 6), want, "OK" if ok else "FAIL"))
        if not ok:
            failures.append(name)

    # -- degenerate FG-1: one diploid founder, R = {that founder}.
    #    Its two genes are at frequency 1/2 each, SUM f^2 = 1/2, N_g = 1 exactly.
    rows = [(1, 0, 0)]
    r = exact_ng(rows, [1])
    check("FG-1 lone founder, R={1}: N_g", r["n_g"], 1.0)

    # -- 1 is NOT a floor. The true floor of 1/2 needs every gene copy in R to
    #    be the SAME founder gene, and that cannot happen while each member of R
    #    still carries one gene from each of two distinct origins.
    #
    #    One offspring of two founders: two distinct genes at 1/2 each, always.
    rows = [(1, 0, 0), (2, 0, 0), (3, 1, 2)]
    dist = distribution(rows, [3])
    check("two founders -> one offspring, R={3}: outcomes", len(dist), 1)
    check("two founders -> one offspring, R={3}: N_g", 1 / (2 * list(dist)[0]), 1.0)

    #    Full sibs cannot reach it either: each still carries one gene of each
    #    parent, so no single gene can exceed frequency 1/2.
    rows = [(1, 0, 0), (2, 0, 0), (4, 1, 2), (5, 1, 2)]
    dist = distribution(rows, [4, 5])
    check("full sibs, R={4,5}: minimum attainable N_g",
          min(1 / (2 * s) for s in dist), 1.0)

    #    Selfing can: animal 4 draws both genes from animal 3, so with
    #    probability 1/2 it draws the same one twice and that gene is FIXED in
    #    R = {4}. N_g = 0.5 is then the correct answer, not an error -- which is
    #    why no postcondition may demand N_g >= 1.
    rows = [(1, 0, 0), (2, 0, 0), (3, 1, 2), (4, 3, 3)]
    dist = distribution(rows, [4])
    check("selfing R={4}: min N_g is fixation, and legal",
          min(1 / (2 * s) for s in dist), 0.5)
    check("selfing R={4}: max N_g", max(1 / (2 * s) for s in dist), 1.0)

    # -- Lacy (1989) Table 1, published H from 10 000 gene drops (p.116).
    published_h = {(2, 2): .812, (3, 3): .833, (4, 4): .844,
                   (2, 4): .819, (4, 8): .840}
    for (n1, n2), h in sorted(published_h.items()):
        rows = [(1, 0, 0), (2, 0, 0), (3, 0, 0), (4, 0, 0)]
        nid, ref = 5, []
        for _ in range(n1):
            rows.append((nid, 1, 2))
            ref.append(nid)
            nid += 1
        for _ in range(n2):
            rows.append((nid, 3, 4))
            ref.append(nid)
            nid += 1
        r = exact_ng(rows, ref, limit=1 << 24)
        check("Lacy Table 1 (%d,%d) H" % (n1, n2), r["h"], h, tol=5e-4 + 1e-9)

    # -- Boichard Table II Family 2, the estimator discriminator (published 1.1).
    rows = [(15, 0, 0), (16, 0, 0), (17, 15, 16), (18, 15, 16),
            (19, 17, 18), (20, 17, 18)]
    r = exact_ng(rows, [19, 20])
    check("Boichard Table II Family 2  E[1/(2S)]  (published 1.1)", r["n_g"], 1.1,
          tol=5e-2 + 1e-9)
    check("Boichard Table II Family 2  1/(2E[S])  (NOT the published value)",
          r["inv_mean_s"], 1.0)

    # -- bounds gate
    ok, worst, slack = check_bounds(rows, [19, 20])
    print("  %-58s %s (min N_g %.4f, min f_e-N_g slack %.4f)"
          % ("bounds 0.5 <= N_g <= f_e_realised, every outcome", "OK" if ok else "FAIL",
             worst, slack))
    if not ok:
        failures.append("bounds")

    print("\n%d failure(s)" % len(failures))
    return 1 if failures else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("pedfile", nargs="?")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--reference", help="e.g. 7-14,19,20")
    ap.add_argument("--gen-col", type=int, default=None)
    ap.add_argument("--gen", help="select R by generation label")
    ap.add_argument("--half-founder", choices=HALF_FOUNDER_MODES, default="phantom")
    ap.add_argument("--replicates", type=int, default=0,
                    help="force Monte Carlo with this many replicates")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--limit", type=int, default=DEFAULT_EXACT_LIMIT)
    a = ap.parse_args()

    if a.self_test:
        return _self_test()
    if not a.pedfile:
        ap.error("a pedfile is required unless --self-test is given")

    rows, gens = read_pedigree(a.pedfile, gen_col=a.gen_col)
    if a.reference:
        reference = _parse_reference(a.reference)
    elif a.gen is not None:
        reference = [x for x, _s, _d in rows if gens.get(x) == a.gen]
    else:
        parents = {p for _a, s, d in rows for p in (s, d) if p != MISSING}
        reference = [x for x, _s, _d in rows if x not in parents]

    if a.replicates:
        out = mc_ng(rows, reference, a.replicates, a.seed, a.half_founder)
        out["method"] = "monte-carlo"
    else:
        out = exact_ng(rows, reference, a.half_founder, a.limit)
        out.pop("n_g_exact")
        out["method"] = "exact-enumeration"
    out["reference"] = sorted(reference)
    out["n_founder_genes_2f"] = len(founder_genes(rows, a.half_founder))
    print(json.dumps(out, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
